services:
  - type: web
    name: assembly-hub
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
